### PR TITLE
feat: add plugin signatures

### PR DESCRIPTION
**Pull request by Puppo**
I added some types to use the type provider into the plugins too!

Feel free to give me your feedbacks

Thanks Luca

### CODE REVIEW

**Comment by Puppo** [comment]
@turkerdev @kibertoad @rupert-mckay any news on this PR?

**Comment by Puppo** [comment]
friendly reminder @turkerdev @kibertoad @rupert-mckay

**Comment by kibertoad** [comment]
checking, sorry!

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
thanks!

**Comment by focux** [comment]
Is this already on NPM?

**Comment by mbirkegaard** [comment]
@focux There's a workaround here in the meantime: https://github.com/turkerdev/fastify-type-provider-zod/issues/75

**Pull request merged**
